package com.wav.pf.entities;
// Generated 21/11/2016 19:27:40 by Hibernate Tools 4.3.1


/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private Integer idendereco;
     private String endereco;
     private String cidade;
     private String estado;
     private String pais;

    public Endereco() {
    }

	
    public Endereco(String endereco, String cidade, String estado, String pais) {
        this.endereco = endereco;
        this.cidade = cidade;
        this.estado = estado;
        this.pais = pais;
    }
   
    public Integer getIdendereco() {
        return this.idendereco;
    }
    
    public void setIdendereco(Integer idendereco) {
        this.idendereco = idendereco;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
}


