package com.wav.pf.entities;
// Generated 21/11/2016 19:27:40 by Hibernate Tools 4.3.1


/**
 * FormaPagamento generated by hbm2java
 */
public class FormaPagamento  implements java.io.Serializable {


     private Integer idformaPagamento;
     private String nome;

    public FormaPagamento() {
    }

	
    public FormaPagamento(String nome) {
        this.nome = nome;
    }
    public Integer getIdformaPagamento() {
        return this.idformaPagamento;
    }
    
    public void setIdformaPagamento(Integer idformaPagamento) {
        this.idformaPagamento = idformaPagamento;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
}


